Code gen main
Team302/2023SummerProject pull request #111
Opened 2023-12-01 12:04 UTC by muscatd75

2024-01-06 03:32 UTC, witcpalek requested changes
I haven't looked at everything, but I don't understand why there is tuning stuff in the mechanism; only the states have things that can be tuned.

2024-01-06 03:32 UTC, witcpalek commented on src/main/cpp/mechanisms/intakeMechanism/generated/intakeMechanism.h
> +	bool m_tuning = false;
Dave, is this still in the generated code?

2024-01-06 03:32 UTC, witcpalek commented on src/main/cpp/mechanisms/ejectMechanism/generated/ejectMechanism.h
> +	std::string m_tuningIsEnabledStr;
Dave - This shouldn't be in the mechanism;  States are where the tuning needs to be.   Joe

2024-01-11 14:05 UTC, muscatd75 commented on src/main/cpp/mechanisms/intakeMechanism/generated/intakeMechanism.h
> +	bool m_tuning = false;
all the mechanism generated code is removed from the pull request

2024-01-11 14:05 UTC, muscatd75 commented on src/main/cpp/mechanisms/intakeMechanism/generated/intakeMechanism.h
> +	void CheckForTuningEnabled();
all the mechanism generated code is removed from the pull request

2024-01-12 20:22 UTC, merged